version: '2.0'
services:
  fluentd:
    image: ${USER_NAME}/search_engine_fluentd:${FLUENTD_VER}
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      appnet:
        aliases:
        - fluentd

  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      appnet:
        aliases:
        - elasticsearch

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    networks:
      appnet:
        aliases:
        - kibana

networks:
  appnet:
    driver: bridge
    ipam:
       config:
       - subnet: 10.0.0.0/24
