global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#pavel_tishkov'