---
global:
  scrape_interval: '5s'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'sec'
    metrics_path: /
    static_configs:
      - targets:
        - 'sec:8000'

  - job_name: 'seu'
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'seu:8000'

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets:
        - 'mongodb-exporter:9216'

  - job_name: 'node'
    static_configs:
      - targets:
        - 'node-exporter:9100'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
